name: Lint, test and build the app

on:
  pull_request:
    types: [opened, synchronize]
    branches: 
      - main
  workflow_dispatch:


jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.x'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.x'

      - name: Install Dependencies
        run: 'bun install --frozen-lockfile'

      - name: Lint
        run: 'bun run lint'